# IMPORTANT: Consult the national team before editing this file. This file catches errors, but can't check itself.

image: node:16.0-slim

stages:
- build
- test
- deploy

cache:
  paths:
    - node_modules/
    - .cache/
    - public

setup:
  stage: build
  script:
    - npm install
    - npm run build

test:
  stage: test
  script:
    - npm test

pages:
  stage: deploy
  script:
    - "# noop"
  artifacts:
    paths:
      - public
  only:
    - master
