# IMPORTANT: Consult the national team before editing this file. This file catches errors, but can't check itself.

image: node:14.0

stages:
  - test
  - deploy

cache:
  paths:
    - node_modules/
    - .cache/
    - public

test:
  stage: test
  script:
    - npm ci
    - npm run build:dev
    - npm test

pages:
  stage: deploy
  script:
    - "# noop"
  artifacts:
    paths:
      - public
  only:
    - master
